//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISA*00*          *00*          *ZZ*99999999999    *ZZ*888888888888   *111219*1340*^*00501*000001377*0*T*&gt;
        ///GS*HC*99999999999*888888888888*20111219*1340*1377*X*005010X222
        ///ST*837*0001*005010X222
        ///BHT*0019*00*565743*20110523*154959*CH
        ///NM1*41*2*SAMPLE INC*****46*496103
        ///PER*IC*EDI DEPT*EM*FEEDBACK@1EDISOURCE.COM*TE*3305551212
        ///NM1*40*2*PPO BLUE*****46*54771
        ///HL*1**20*1
        ///PRV*BI*PXC*333600000X
        ///NM1*85*2*EDI SPECIALTY SAMPLE*****XX*123456789
        ///N3*1212 DEPOT DRIVE
        ///N4*CHICAGO*IL*606930159
        ///REF*EI*300123456
        ///HL*2*1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDI_837 {
            get {
                return ResourceManager.GetString("EDI_837", resourceCulture);
            }
        }
    }
}
